#!/bin/bash

git config --global user.name "CI-Server"
git config --global user.email "ci@example.com"
git remote set-url origin git@github.com:AngelicaDesign/angelicadesign.github.io.git

# Install dependencies for image resizing
curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -

npm install
npm install -g bower
bower install
